### ISSUE TITLE
column command got invalid option -n

### ISSUE THREAD

**Issue by zer09** [ryanoasis/devicons-shell#1]
Hello good day,

Just want to ask  I am getting this error if I tried to run the devicons-ls.
```column: invalid option -- 'n'```
I tried ```man column``` but it seems I cant find the -n option.
Can you give a hint how I can fix this? please.

Thanks

**Comment by ryanoasis** [comment]
@zer09 Are you on Arch Linux?

I believe it is a version of `column` issue that doesn't support that option.

Check this comment out, it might be helpful: https://www.reddit.com/r/unixporn/comments/6ea1em/oc_customizable_ls_icons_link_in_comments/di96lac/

**Comment by zer09** [comment]
Got it thanks, but I will just wait the official release of fedora 26, I tried it on VM and woks perfectly. I am now on fedora 25 that has version 2.28 of column command.

Thanks

**Comment by zer09** [comment]
opss, I was wrong, I forgot I did change the ```-n``` option with ```-x```. I will try to read the reddit link you give.
